### ISSUE TITLE
Override config fields with environment variables

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/config-loader#17]
For example, if we have the following config:

```yaml
database:
  mongodb:
    uri: mongodb://localhost:27017
```

Then we should able to override its values via env vars as follows:

export CONFIG_DATABASE_MONGODB_URI=mongodb://localhost:1234
